const KEY = 'matriz-multi-skill-local-v1';
const levels = [['titular','Titular','T'],['nivel_1','Nível 1','N1'],['nivel_2','Nível 2','N2'],['nivel_3','Nível 3','N3'],['formacao_planejada','Formação planejada','FP'],['sem_habilitacao','Sem habilitação','—']];
const defaultEmployees = ['Marlene','Natan','Cassiane','Ronald','Alisson','Izabele','Ivana','Maria Eduarda','Anderson Santos','Jeisse','Marcia Souza','Marcia Seguro','Richard','Maria','Larissa','Alisson Douglas','Francieli'];
const defaultOperations = ['07SM 11 D','07SM 11 E','07SM 12 D','07SM 12 E','07SM 13','07SM 14','07SM 15','07SM 16','07SM 50','07SM 51','07SM 52 1','07SM 52 2','07SM 53'];
const titularMap = {'07SM 11 D':'Marlene','07SM 11 E':'Natan','07SM 12 D':'Cassiane','07SM 12 E':'Alisson','07SM 13':'Anderson Santos','07SM 14':'Maria Eduarda','07SM 15':'Ivana','07SM 16':'Jeisse','07SM 50':'Maria','07SM 51':'Izabele','07SM 52 1':'Marcia Souza','07SM 52 2':'Richard','07SM 53':'Larissa'};
let state = load(); let modalMode = null; let modalId = null; let draggedRoute = null;
function blankPlan(id, name){ return {id, name, mode:'manual', frequency:'daily', scheduledDate:'', assignments:{}, lastRun:'', rotationRoutes:{}, history:[]}; }
function migratePlan(p, i=0){ const plan = {...blankPlan(p?.id || 'line-'+(i+1), p?.name || 'Linha '+(i+1)), ...(p||{})}; plan.assignments = {...(p?.assignments||{})}; plan.rotationRoutes = {...(p?.rotationRoutes||{})}; plan.history = Array.isArray(p?.history) ? p.history : []; return plan; }
function load(){
  try { const saved = JSON.parse(localStorage.getItem(KEY)); if(saved){ const base = {...saved}; base.linePlans = Array.isArray(saved.linePlans) && saved.linePlans.length ? saved.linePlans.map(migratePlan) : [migratePlan(saved.linePlan)]; base.activeLineId = saved.activeLineId || base.linePlans[0].id; delete base.linePlan; return base; } } catch(e){}
  const employees = defaultEmployees.map((name,i)=>({id:'e'+i,name})); const operations = defaultOperations.map((code,i)=>({id:'o'+i,code})); const skills = {};
  operations.forEach(o=>{const emp=employees.find(e=>e.name===titularMap[o.code]);if(emp)skills[emp.id+'|'+o.id]='titular'});
  return {employees,operations,skills,linePlans:[blankPlan('line-1','Linha 1')],activeLineId:'line-1'};
}
function save(){ localStorage.setItem(KEY, JSON.stringify(state)); }
function activePlan(){ return state.linePlans.find(l=>l.id===state.activeLineId) || state.linePlans[0]; }
function escapeHtml(s){ return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function levelInfo(v){ return levels.find(x=>x[0]===v)||levels[5]; }
function skill(e,o){ return state.skills[e+'|'+o]||'sem_habilitacao'; }
function coverageEmployee(id){ return state.operations.filter(o=>skill(id,o.id)!=='sem_habilitacao').length; }
function coverageOperation(id){ return state.employees.filter(e=>skill(e.id,id)!=='sem_habilitacao').length; }
function today(){ return new Date().toISOString().slice(0,10); }
function recordHistory(reason, plan=activePlan()){
  const snapshot = {id:'h'+Date.now(), date:today(), timestamp:new Date().toISOString(), reason, lineId:plan.id, lineName:plan.name, assignments:{...plan.assignments}};
  plan.history = [snapshot, ...(plan.history||[])].slice(0,120); return snapshot;
}
function render(){ maybeRunScheduledRotation(); const total=state.employees.length*state.operations.length; const covered=state.employees.reduce((a,e)=>a+coverageEmployee(e.id),0); const planned=Object.values(state.skills).filter(x=>x==='formacao_planejada').length;
  document.querySelector('#stats').innerHTML=[['Cobertura geral',total?Math.round(covered/total*100)+'%':'0%',`${covered} de ${total} posições`,'▦'],['Funcionários',state.employees.length,'pessoas na matriz','♙'],['Operações',state.operations.length,'postos acompanhados','↕'],['Formações planejadas',planned,'pontos de atenção','⌂']].map(x=>`<div class="stat"><span class="stat-label">${x[0]}</span><div class="stat-value">${x[1]}</div><span class="stat-helper">${x[2]}</span></div>`).join('');
  const query=(document.querySelector('#searchInput')?.value||'').toLowerCase(); const emps=state.employees.filter(e=>e.name.toLowerCase().includes(query)); let html='<thead><tr><th>Funcionário</th>'+state.operations.map(o=>`<th><button class="operation-head" data-edit-operation="${o.id}">${escapeHtml(o.code)} ✎</button><div>${coverageOperation(o.id)} habilitados <button class="operation-delete" data-delete-operation="${o.id}" title="Remover">×</button></div></th>`).join('')+'<th>Cobertura</th></tr></thead><tbody>';
  html += emps.map(e=>`<tr><td><span class="initials">${e.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><button class="employee-name" data-edit-employee="${e.id}">${escapeHtml(e.name)}</button><button class="employee-delete" data-delete-employee="${e.id}" title="Remover">×</button></td>${state.operations.map(o=>{const v=skill(e.id,o.id);return `<td><select class="cell-select ${v}" data-employee="${e.id}" data-operation="${o.id}">${levels.map(l=>`<option value="${l[0]}" ${l[0]===v?'selected':''}>${l[1]}</option>`).join('')}</select></td>`}).join('')}<td class="coverage ${coverageEmployee(e.id)<Math.ceil(state.operations.length/2)?'low':'ok'}">${coverageEmployee(e.id)}/${state.operations.length}</td></tr>`).join(''); html+='</tbody>'; document.querySelector('#matrixTable').innerHTML=html; document.querySelector('#legend').innerHTML=levels.map(l=>`<span><b class="${l[0]}">${l[2]}</b>${l[1]}</span>`).join(''); renderSummaries(emps); bindMatrixEvents(); }
function renderSummaries(emps){ document.querySelector('#employeeSummary').innerHTML=emps.slice(0,8).map(e=>bar(e.name,coverageEmployee(e.id),state.operations.length)).join('')||'<p class="local-note">Nenhum funcionário encontrado.</p>'; document.querySelector('#operationSummary').innerHTML=state.operations.slice(0,8).map(o=>bar(o.code,coverageOperation(o.id),state.employees.length)).join(''); renderLineBoard(); }
function bar(label,value,total){const pct=total?Math.round(value/total*100):0;return `<div class="summary-item"><div class="summary-line"><span>${escapeHtml(label)}</span><strong class="${pct<50?'low':'ok'}">${value}/${total}</strong></div><div class="bar"><i class="${pct<50?'warning':''}" style="width:${pct}%"></i></div></div>`;}
function renderLineBoard(){ const plan=activePlan(); if(!plan)return; const board=document.querySelector('#lineBoard'); const banner=document.querySelector('#rotationBanner'); const lineSelect=document.querySelector('#lineSelect'); if(lineSelect)lineSelect.innerHTML=state.linePlans.map(l=>`<option value="${l.id}" ${l.id===plan.id?'selected':''}>${escapeHtml(l.name)}</option>`).join(''); document.querySelector('#rotationDate').value=plan.scheduledDate||''; document.querySelector('#rotationFrequency').value=plan.frequency||'daily'; document.querySelector('#rotationMode').value=plan.mode||'manual';
  const currentDay=today(); if(plan.mode==='automatic'&&plan.scheduledDate){ if(plan.lastRun===currentDay) banner.innerHTML=`Rotação automática executada hoje. Próxima execução prevista para: <strong>${plan.scheduledDate}</strong>`; else if(currentDay>=plan.scheduledDate) banner.innerHTML=`<strong>Atenção:</strong> A data programada (${plan.scheduledDate}) venceu. A rotação será executada automaticamente.`; else banner.innerHTML=`Próxima rotação automática agendada para: <strong>${plan.scheduledDate}</strong>`; } else banner.innerHTML='Modo manual ativo. A rotação não ocorrerá automaticamente.';
  board.innerHTML=state.operations.map(o=>{const empId=plan.assignments[o.id];const emp=state.employees.find(e=>e.id===empId);const lv=emp?skill(emp.id,o.id):'sem_habilitacao';const info=levelInfo(lv);return `<div class="step-card"><div class="step-head"><div class="step-code">${escapeHtml(o.code)}</div><div class="step-meta"><span>Step</span><span class="mode-pill ${plan.mode}">${plan.mode==='automatic'?'automática':'manual'}</span></div></div><div class="step-body">${emp?`<div class="assembler"><div class="assembler-avatar">${emp.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</div><div><div class="assembler-name">${escapeHtml(emp.name)}</div><small class="assembler-level ${lv}">${info[1]}</small></div><button class="operation-delete" onclick="assign('${o.id}',null)" title="Remover">×</button></div>`:'<div class="empty-step">Nenhum montador alocado</div>'}<button class="step-add" onclick="openAssignModal('${o.id}')">＋ Alocar montador</button></div></div>`}).join(''); renderRouteEditor(); renderHistory(); }
function renderRouteEditor(){ const el=document.querySelector('#routeEditor'); if(!el)return; el.innerHTML=state.employees.map(emp=>{const eligible=eligibleOperations(emp.id).map(o=>o.id);const route=routeFor(emp.id);const hasCustom=Array.isArray(activePlan().rotationRoutes?.[emp.id]);if(!eligible.length)return `<div class="route-row"><div class="route-person"><strong>${escapeHtml(emp.name)}</strong><small>Nenhum step habilitado</small></div><span class="route-empty">Cadastre habilitações na matriz.</span></div>`;return `<div class="route-row"><div class="route-person"><strong>${escapeHtml(emp.name)}</strong><small>${hasCustom?'Rota personalizada':'Rota padrão pelos steps habilitados'}</small></div><div class="route-dropzone" data-route-employee="${emp.id}">${route.map((opId,i)=>{const op=state.operations.find(o=>o.id===opId);return `<div class="route-item" draggable="true" data-route-employee="${emp.id}" data-route-index="${i}"><span class="drag-handle">⋮⋮</span><span class="route-number">${i+1}</span><strong>${escapeHtml(op?.code||'Step removido')}</strong></div>`}).join('')||'<span class="route-empty">Arraste steps habilitados para esta rota.</span>'}</div><button class="btn secondary route-reset" data-route-reset="${emp.id}">${hasCustom?'Usar padrão':'Rota padrão'}</button></div>`}).join(''); bindRouteEvents(); }
function renderHistory(){ const el=document.querySelector('#historyList'); if(!el)return; const rows=state.linePlans.flatMap(p=>(p.history||[]).map(h=>({...h,lineName:p.name}))).sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp))).slice(0,30); el.innerHTML=rows.length?rows.map(h=>{const count=Object.keys(h.assignments||{}).length;return `<div class="history-item"><div><strong>${escapeHtml(h.lineName)}</strong><span>${escapeHtml(h.reason)}</span></div><div class="history-meta"><b>${h.date}</b><small>${new Date(h.timestamp).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · ${count} alocado(s)</small></div></div>`}).join(''):'<p class="local-note">Nenhum registro ainda. As alterações de escala e rotações aparecerão aqui.</p>'; }
function eligibleOperations(empId){return state.operations.filter(o=>skill(empId,o.id)!=='sem_habilitacao');}
function routeFor(empId){const eligible=eligibleOperations(empId).map(o=>o.id);const saved=activePlan().rotationRoutes?.[empId];if(Array.isArray(saved)&&saved.length)return saved.filter(id=>eligible.includes(id));return eligible;}
function saveRouteOrder(empId,ids){const unique=[...new Set(ids)].filter(id=>eligibleOperations(empId).some(o=>o.id===id));const plan=activePlan();if(unique.length)plan.rotationRoutes[empId]=unique;else delete plan.rotationRoutes[empId];recordHistory('Rota personalizada atualizada',plan);save();renderLineBoard();flash('Ordem da rota salva');}
function bindRouteEvents(){document.querySelectorAll('.route-item').forEach(item=>{item.addEventListener('dragstart',()=>{draggedRoute={empId:item.dataset.routeEmployee,index:Number(item.dataset.routeIndex)};item.classList.add('dragging')});item.addEventListener('dragend',()=>{draggedRoute=null;item.classList.remove('dragging')});});document.querySelectorAll('.route-dropzone').forEach(zone=>{zone.addEventListener('dragover',e=>e.preventDefault());zone.addEventListener('drop',e=>{e.preventDefault();if(!draggedRoute||draggedRoute.empId!==zone.dataset.routeEmployee)return;const target=e.target.closest('.route-item');const route=routeFor(draggedRoute.empId);const from=draggedRoute.index;let to=target?Number(target.dataset.routeIndex):route.length;if(from===to||(!target&&from===route.length-1))return;const [moved]=route.splice(from,1);if(target&&from<to)to--;route.splice(Math.max(0,to),0,moved);saveRouteOrder(draggedRoute.empId,route);});});document.querySelectorAll('[data-route-reset]').forEach(b=>b.onclick=()=>{delete activePlan().rotationRoutes[b.dataset.routeReset];recordHistory('Rota voltou ao padrão',activePlan());save();renderLineBoard();flash('Rota padrão restaurada');});}
function openAssignModal(opId){modalMode='assign';modalId=opId;document.querySelector('#modalTitle').textContent='Alocar montador';document.querySelector('#modalLabel').textContent='Selecione o funcionário';const op=state.operations.find(o=>o.id===opId);const plan=activePlan();const eligible=state.employees.filter(e=>skill(e.id,opId)!=='sem_habilitacao'&&!Object.entries(plan.assignments).some(([id,emp])=>id!==opId&&emp===e.id));const options=eligible.map(e=>{const info=levelInfo(skill(e.id,opId));return `<option value="${e.id}">${escapeHtml(e.name)} (${info[1]})</option>`}).join('')||'<option value="">Nenhum montador habilitado ou disponível</option>';document.querySelector('#modalInput').outerHTML=`<select id="modalInput" class="modal-select"><option value="">Selecione...</option>${options}</select>`;document.querySelector('#modalBackdrop').classList.remove('hidden');}
function assign(opId,empId){const plan=activePlan();Object.keys(plan.assignments).forEach(id=>{if(id!==opId&&plan.assignments[id]===empId)delete plan.assignments[id]});if(empId)plan.assignments[opId]=empId;else delete plan.assignments[opId];recordHistory(empId?'Alocação manual atualizada':'Alocação removida',plan);save();render();flash(empId?'Montador alocado':'Alocação removida');}
function rotateAssignments(){const plan=activePlan();const current={...plan.assignments};const desired=[];Object.entries(current).forEach(([currentOpId,empId])=>{const route=routeFor(empId);if(!route.length)return;const index=route.indexOf(currentOpId);const nextOpId=route[(index<0?0:index+1)%route.length];desired.push({currentOpId,empId,nextOpId});});const newAssignments={};desired.forEach(({currentOpId,empId,nextOpId})=>{if(!newAssignments[nextOpId])newAssignments[nextOpId]=empId;else if(!newAssignments[currentOpId])newAssignments[currentOpId]=empId;});plan.assignments=newAssignments;plan.lastRun=today();if(plan.scheduledDate){const date=new Date(plan.scheduledDate+'T00:00:00');date.setDate(date.getDate()+(plan.frequency==='daily'?1:7));plan.scheduledDate=date.toISOString().slice(0,10);}recordHistory('Rotação '+(plan.mode==='automatic'?'automática':'manual'),plan);}
function maybeRunScheduledRotation(){const plan=activePlan();const day=today();if(plan.mode==='automatic'&&plan.scheduledDate&&day>=plan.scheduledDate&&plan.lastRun!==day){rotateAssignments();save();}}
function runRotation(){rotateAssignments();save();render();flash('Rotação concluída com sucesso');}
function barDummy(){}
function bindMatrixEvents(){document.querySelectorAll('.cell-select').forEach(s=>s.onchange=()=>{state.skills[s.dataset.employee+'|'+s.dataset.operation]=s.value;save();render();flash('Habilitação salva');});document.querySelectorAll('[data-edit-employee]').forEach(b=>b.onclick=()=>openModal('employee',b.dataset.editEmployee));document.querySelectorAll('[data-delete-employee]').forEach(b=>b.onclick=()=>{if(confirm('Remover este funcionário da matriz?')){state.employees=state.employees.filter(e=>e.id!==b.dataset.deleteEmployee);state.linePlans.forEach(p=>{delete p.rotationRoutes[b.dataset.deleteEmployee];Object.keys(p.assignments).forEach(o=>{if(p.assignments[o]===b.dataset.deleteEmployee)delete p.assignments[o];});});save();render();flash('Funcionário removido');}});document.querySelectorAll('[data-edit-operation]').forEach(b=>b.onclick=()=>openModal('operation',b.dataset.editOperation));document.querySelectorAll('[data-delete-operation]').forEach(b=>b.onclick=()=>{if(confirm('Remover esta operação da matriz?')){state.operations=state.operations.filter(o=>o.id!==b.dataset.deleteOperation);state.linePlans.forEach(p=>{delete p.assignments[b.dataset.deleteOperation];Object.keys(p.rotationRoutes).forEach(e=>p.rotationRoutes[e]=p.rotationRoutes[e].filter(id=>id!==b.dataset.deleteOperation));});save();render();flash('Operação removida');}});}
function openLineModal(id=null){modalMode='line';modalId=id;document.querySelector('#modalTitle').textContent=id?'Editar linha':'Adicionar linha';document.querySelector('#modalLabel').textContent='Nome da linha';document.querySelector('#modalInput').value=id?(state.linePlans.find(l=>l.id===id)?.name||''):'';document.querySelector('#modalBackdrop').classList.remove('hidden');document.querySelector('#modalInput').focus();}
function openModal(mode,id=null){modalMode=mode;modalId=id;document.querySelector('#modalTitle').textContent=id?(mode==='employee'?'Editar funcionário':'Editar operação'):(mode==='employee'?'Adicionar funcionário':'Adicionar operação');document.querySelector('#modalLabel').textContent=mode==='employee'?'Nome completo':'Código da operação';document.querySelector('#modalInput').value=id?(mode==='employee'?state.employees.find(e=>e.id===id).name:state.operations.find(o=>o.id===id).code):'';document.querySelector('#modalBackdrop').classList.remove('hidden');document.querySelector('#modalInput').focus();}
function closeModal(){document.querySelector('#modalBackdrop').classList.add('hidden');const select=document.querySelector('.modal-select');if(select)select.outerHTML='<input id="modalInput" autocomplete="off">';modalMode=null;modalId=null;}
function saveModal(){const input=document.querySelector('#modalInput');const value=input.value.trim();if(modalMode==='assign'){if(value)assign(modalId,value);closeModal();return;}if(value.length<2)return;if(modalMode==='line'){if(modalId)state.linePlans.find(l=>l.id===modalId).name=value;else{const id='line-'+Date.now();state.linePlans.push(blankPlan(id,value));state.activeLineId=id;}save();closeModal();renderLineBoard();flash('Linha salva');return;}if(modalMode==='employee'){if(modalId)state.employees.find(e=>e.id===modalId).name=value;else state.employees.push({id:'e'+Date.now(),name:value});}else{if(modalId)state.operations.find(o=>o.id===modalId).code=value;else state.operations.push({id:'o'+Date.now(),code:value});}save();closeModal();render();flash('Alteração salva');}
function deleteActiveLine(){if(state.linePlans.length<=1){flash('Mantenha pelo menos uma linha');return;}if(confirm('Remover esta linha e seu histórico?')){state.linePlans=state.linePlans.filter(l=>l.id!==activePlan().id);state.activeLineId=state.linePlans[0].id;save();renderLineBoard();flash('Linha removida');}}
function exportJson(){const payload={format:'Matriz Multi Skill Local',version:2,exportedAt:new Date().toISOString(),employees:state.employees,operations:state.operations,skills:state.skills,linePlans:state.linePlans,activeLineId:state.activeLineId};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='matriz-multi-skill-'+today()+'.json';a.click();URL.revokeObjectURL(url);flash('JSON exportado com sucesso');}
function validImport(data){if(!data||!Array.isArray(data.employees)||!Array.isArray(data.operations)||!data.skills||typeof data.skills!=='object'||!data.employees.length||!data.operations.length)return false;const eids=new Set(),oids=new Set(),allowed=new Set(levels.map(l=>l[0]));if(data.employees.some(e=>!e||typeof e.id!=='string'||!e.id.trim()||typeof e.name!=='string'||!e.name.trim()||eids.has(e.id)))return false;data.employees.forEach(e=>eids.add(e.id));if(data.operations.some(o=>!o||typeof o.id!=='string'||!o.id.trim()||typeof o.code!=='string'||!o.code.trim()||oids.has(o.id)))return false;data.operations.forEach(o=>oids.add(o.id));if(!Object.entries(data.skills).every(([k,v])=>{const p=k.split('|');return p.length===2&&eids.has(p[0])&&oids.has(p[1])&&typeof v==='string'&&allowed.has(v)}))return false;const plans=Array.isArray(data.linePlans)?data.linePlans:(data.linePlan?[data.linePlan]:[]);if(plans.length===0)return false;return plans.every(p=>p&&typeof p==='object'&&typeof (p.name||'Linha')==='string'&&(!p.assignments||Object.entries(p.assignments).every(([o,e])=>oids.has(o)&&eids.has(e))));}
function importJson(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!validImport(data))throw new Error('Formato inválido');const rawPlans=Array.isArray(data.linePlans)?data.linePlans:(data.linePlan?[data.linePlan]:[]);state={employees:data.employees.map(e=>({id:e.id.trim(),name:e.name.trim()})),operations:data.operations.map(o=>({id:o.id.trim(),code:o.code.trim()})),skills:{...data.skills},linePlans:rawPlans.map((p,i)=>migratePlan({...p,id:p.id||'line-'+(i+1),name:p.name||'Linha '+(i+1)},i)),activeLineId:data.activeLineId||rawPlans[0].id||'line-1'};if(!state.linePlans.some(p=>p.id===state.activeLineId))state.activeLineId=state.linePlans[0].id;save();render();flash('JSON importado com sucesso');}catch(e){flash('Não foi possível importar este JSON');}};reader.readAsText(file);}
function flash(message){const n=document.createElement('div');n.textContent=message;n.style='position:fixed;right:20px;bottom:20px;background:#0f172a;color:white;padding:12px 16px;border-radius:10px;z-index:9;font-weight:600;font-size:13px;box-shadow:0 10px 30px #0003';document.body.appendChild(n);setTimeout(()=>n.remove(),1800);}
function showMatrix(){document.querySelector('#matriz').classList.remove('hidden');document.querySelector('.summary-grid').classList.remove('hidden');document.querySelector('#lineScreen').classList.add('hidden');document.querySelector('#matrixNav').classList.add('active');document.querySelector('#lineNav').classList.remove('active');}
function showLine(){document.querySelector('#matriz').classList.add('hidden');document.querySelector('.summary-grid').classList.add('hidden');document.querySelector('#lineScreen').classList.remove('hidden');document.querySelector('#matrixNav').classList.remove('active');document.querySelector('#lineNav').classList.add('active');renderLineBoard();}
document.querySelector('#searchInput').addEventListener('input',render);document.querySelector('#exportBtn').onclick=exportJson;document.querySelector('#importBtn').onclick=()=>document.querySelector('#importFile').click();document.querySelector('#importFile').onchange=e=>{if(e.target.files[0])importJson(e.target.files[0]);e.target.value=''};document.querySelector('#addEmployeeBtn').onclick=()=>openModal('employee');document.querySelector('#addOperationBtn').onclick=()=>openModal('operation');document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#cancelModal').onclick=closeModal;document.querySelector('#saveModal').onclick=saveModal;document.querySelector('#modalInput').onkeydown=e=>{if(e.key==='Enter')saveModal();if(e.key==='Escape')closeModal()};document.querySelector('#matrixNav').onclick=e=>{e.preventDefault();showMatrix();};document.querySelector('#lineNav').onclick=showLine;document.querySelector('#rotationDate').onchange=e=>{activePlan().scheduledDate=e.target.value;save();renderLineBoard();};document.querySelector('#rotationFrequency').onchange=e=>{activePlan().frequency=e.target.value;save();renderLineBoard();};document.querySelector('#rotationMode').onchange=e=>{activePlan().mode=e.target.value;save();renderLineBoard();};document.querySelector('#runRotationBtn').onclick=runRotation;document.querySelector('#lineSelect').onchange=e=>{state.activeLineId=e.target.value;save();renderLineBoard();};document.querySelector('#addLineBtn').onclick=()=>openLineModal();document.querySelector('#editLineBtn').onclick=()=>openLineModal(activePlan().id);document.querySelector('#deleteLineBtn').onclick=deleteActiveLine;window.assign=assign;window.openAssignModal=openAssignModal;window.saveRouteOrder=saveRouteOrder;window.openLineModal=openLineModal;render();setInterval(()=>{const plan=activePlan();const day=today();if(plan.mode==='automatic'&&plan.scheduledDate&&day>=plan.scheduledDate&&plan.lastRun!==day){rotateAssignments();save();render();flash('Rotação automática executada');}},60000);
