const KEY = 'matriz-multi-skill-local-v1';
const levels = [['titular','Titular','T'],['nivel_1','Nível 1','N1'],['nivel_2','Nível 2','N2'],['nivel_3','Nível 3','N3'],['formacao_planejada','Formação planejada','FP'],['sem_habilitacao','Sem habilitação','—']];
const defaultEmployees = ['Marlene','Natan','Cassiane','Ronald','Alisson','Izabele','Ivana','Maria Eduarda','Anderson Santos','Jeisse','Marcia Souza','Marcia Seguro','Richard','Maria','Larissa','Alisson Douglas','Francieli'];
const defaultOperations = ['07SM 11 D','07SM 11 E','07SM 12 D','07SM 12 E','07SM 13','07SM 14','07SM 15','07SM 16','07SM 50','07SM 51','07SM 52 1','07SM 52 2','07SM 53'];
const titularMap = {'07SM 11 D':'Marlene','07SM 11 E':'Natan','07SM 12 D':'Cassiane','07SM 12 E':'Alisson','07SM 13':'Anderson Santos','07SM 14':'Maria Eduarda','07SM 15':'Ivana','07SM 16':'Jeisse','07SM 50':'Maria','07SM 51':'Izabele','07SM 52 1':'Marcia Souza','07SM 52 2':'Richard','07SM 53':'Larissa'};
let state = load(); let modalMode = null; let modalId = null; let draggedRoute = null; let pendingSuggestion = null;
function blankPlan(id, name){ return {id, name, mode:'manual', frequency:'daily', scheduledDate:'', assignments:{}, lastRun:'', rotationRoutes:{}}; }
function migratePlan(p, i=0){ const plan = {...blankPlan(p?.id || 'line-'+(i+1), p?.name || 'Linha '+(i+1)), ...(p||{})}; plan.assignments = {...(p?.assignments||{})}; plan.rotationRoutes = {...(p?.rotationRoutes||{})}; delete plan.history; return plan; }
function matrixFromState(source,id,name){const linePlans=Array.isArray(source.linePlans)&&source.linePlans.length?source.linePlans.map(migratePlan):[migratePlan(source.linePlan)];return {id,name,employees:(source.employees||[]).map(e=>({...e})),operations:(source.operations||[]).map(o=>({...o})),skills:{...(source.skills||{})},linePlans,activeLineId:source.activeLineId||linePlans[0].id};}
function activateMatrix(id){const matrix=state.matrices.find(m=>m.id===id)||state.matrices[0];if(!matrix)return;state.activeMatrixId=matrix.id;state.employees=matrix.employees;state.operations=matrix.operations;state.skills=matrix.skills;state.linePlans=matrix.linePlans;state.activeLineId=matrix.activeLineId||matrix.linePlans[0].id;}
function syncCurrentMatrix(){if(!state?.matrices)return;const matrix=state.matrices.find(m=>m.id===state.activeMatrixId);if(!matrix)return;matrix.employees=state.employees;matrix.operations=state.operations;matrix.skills=state.skills;matrix.linePlans=state.linePlans;matrix.activeLineId=state.activeLineId;}
function load(){
  try { const saved = JSON.parse(localStorage.getItem(KEY)); if(saved){ const matrices=Array.isArray(saved.matrices)&&saved.matrices.length?saved.matrices.map((m,i)=>matrixFromState(m,m.id||'table-'+(i+1),m.name||'Tabela '+(i+1))):[matrixFromState(saved,'table-1','Tabela 1')]; const base={matrices,activeMatrixId:saved.activeMatrixId||matrices[0].id}; const first=matrices.find(m=>m.id===base.activeMatrixId)||matrices[0]; base.activeMatrixId=first.id;base.employees=first.employees;base.operations=first.operations;base.skills=first.skills;base.linePlans=first.linePlans;base.activeLineId=first.activeLineId; return base; } } catch(e){}
  const employees = defaultEmployees.map((name,i)=>({id:'e'+i,name})); const operations = defaultOperations.map((code,i)=>({id:'o'+i,code})); const skills = {};
  operations.forEach(o=>{const emp=employees.find(e=>e.name===titularMap[o.code]);if(emp)skills[emp.id+'|'+o.id]='titular'});
  const first={employees,operations,skills,linePlans:[blankPlan('line-1','Linha 1')],activeLineId:'line-1'};return {...matrixFromState(first,'table-1','Tabela 1'),matrices:[matrixFromState(first,'table-1','Tabela 1')],activeMatrixId:'table-1'};
}
function save(){ syncCurrentMatrix(); localStorage.setItem(KEY, JSON.stringify(state)); }
function activePlan(){ return state.linePlans.find(l=>l.id===state.activeLineId) || state.linePlans[0]; }
function escapeHtml(s){ return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function levelInfo(v){ return levels.find(x=>x[0]===v)||levels[5]; }
function skill(e,o){ return state.skills[e+'|'+o]||'sem_habilitacao'; }
function coverageEmployee(id){ return state.operations.filter(o=>skill(id,o.id)!=='sem_habilitacao').length; }
function coverageOperation(id){ return state.employees.filter(e=>skill(e.id,id)!=='sem_habilitacao').length; }
function today(){ return new Date().toISOString().slice(0,10); }

function renderMatrixSelector(){const el=document.querySelector('#matrixSelect');if(el)el.innerHTML=state.matrices.map(m=>`<option value="${m.id}" ${m.id===state.activeMatrixId?'selected':''}>${escapeHtml(m.name)}</option>`).join('');}
function render(){ maybeRunScheduledRotation(); renderMatrixSelector(); const total=state.employees.length*state.operations.length; const covered=state.employees.reduce((a,e)=>a+coverageEmployee(e.id),0); const planned=Object.values(state.skills).filter(x=>x==='formacao_planejada').length;
  document.querySelector('#stats').innerHTML=[['Cobertura geral',total?Math.round(covered/total*100)+'%':'0%',`${covered} de ${total} posições`,'▦'],['Funcionários',state.employees.length,'pessoas na matriz','♙'],['Operações',state.operations.length,'postos acompanhados','↕'],['Formações planejadas',planned,'pontos de atenção','⌂']].map(x=>`<div class="stat"><span class="stat-label">${x[0]}</span><div class="stat-value">${x[1]}</div><span class="stat-helper">${x[2]}</span></div>`).join('');
  const query=(document.querySelector('#searchInput')?.value||'').toLowerCase(); const emps=state.employees.filter(e=>e.name.toLowerCase().includes(query)); let html='<thead><tr><th>Funcionário</th>'+state.operations.map(o=>`<th><button class="operation-head" data-edit-operation="${o.id}">${escapeHtml(o.code)} ✎</button><div>${coverageOperation(o.id)} habilitados <button class="operation-delete" data-delete-operation="${o.id}" title="Remover">×</button></div></th>`).join('')+'<th>Cobertura</th></tr></thead><tbody>';
  html += emps.map(e=>`<tr><td><span class="initials">${e.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><button class="employee-name" data-edit-employee="${e.id}">${escapeHtml(e.name)}</button><button class="employee-delete" data-delete-employee="${e.id}" title="Remover">×</button></td>${state.operations.map(o=>{const v=skill(e.id,o.id);return `<td><select class="cell-select ${v}" data-employee="${e.id}" data-operation="${o.id}">${levels.map(l=>`<option value="${l[0]}" ${l[0]===v?'selected':''}>${l[1]}</option>`).join('')}</select></td>`}).join('')}<td class="coverage ${coverageEmployee(e.id)<Math.ceil(state.operations.length/2)?'low':'ok'}">${coverageEmployee(e.id)}/${state.operations.length}</td></tr>`).join(''); html+='</tbody>'; document.querySelector('#matrixTable').innerHTML=html; document.querySelector('#legend').innerHTML=levels.map(l=>`<span><b class="${l[0]}">${l[2]}</b>${l[1]}</span>`).join(''); renderSummaries(emps); bindMatrixEvents(); }
function renderSummaries(emps){ document.querySelector('#employeeSummary').innerHTML=emps.slice(0,8).map(e=>bar(e.name,coverageEmployee(e.id),state.operations.length)).join('')||'<p class="local-note">Nenhum funcionário encontrado.</p>'; document.querySelector('#operationSummary').innerHTML=state.operations.slice(0,8).map(o=>bar(o.code,coverageOperation(o.id),state.employees.length)).join(''); renderLineBoard(); }
function bar(label,value,total){const pct=total?Math.round(value/total*100):0;return `<div class="summary-item"><div class="summary-line"><span>${escapeHtml(label)}</span><strong class="${pct<50?'low':'ok'}">${value}/${total}</strong></div><div class="bar"><i class="${pct<50?'warning':''}" style="width:${pct}%"></i></div></div>`;}
function renderLineBoard(){ const plan=activePlan(); if(!plan)return; const board=document.querySelector('#lineBoard'); const banner=document.querySelector('#rotationBanner'); const lineSelect=document.querySelector('#lineSelect'); if(lineSelect)lineSelect.innerHTML=state.linePlans.map(l=>`<option value="${l.id}" ${l.id===plan.id?'selected':''}>${escapeHtml(l.name)}</option>`).join(''); document.querySelector('#rotationDate').value=plan.scheduledDate||''; document.querySelector('#rotationFrequency').value=plan.frequency||'daily'; document.querySelector('#rotationMode').value=plan.mode||'manual';
  const currentDay=today(); if(plan.mode==='automatic'&&plan.scheduledDate){ if(plan.lastRun===currentDay) banner.innerHTML=`Rotação automática executada hoje. Próxima execução prevista para: <strong>${plan.scheduledDate}</strong>`; else if(currentDay>=plan.scheduledDate) banner.innerHTML=`<strong>Atenção:</strong> A data programada (${plan.scheduledDate}) venceu. A rotação será executada automaticamente.`; else banner.innerHTML=`Próxima rotação automática agendada para: <strong>${plan.scheduledDate}</strong>`; } else banner.innerHTML='Modo manual ativo. A rotação não ocorrerá automaticamente.';
  board.innerHTML=state.operations.map(o=>{const empId=plan.assignments[o.id];const emp=state.employees.find(e=>e.id===empId);const lv=emp?skill(emp.id,o.id):'sem_habilitacao';const info=levelInfo(lv);return `<div class="step-card"><div class="step-head"><div class="step-code">${escapeHtml(o.code)}</div><div class="step-meta"><span>Step</span><span class="mode-pill ${plan.mode}">${plan.mode==='automatic'?'automática':'manual'}</span></div></div><div class="step-body">${emp?`<div class="assembler"><div class="assembler-avatar">${emp.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</div><div><div class="assembler-name">${escapeHtml(emp.name)}</div><small class="assembler-level ${lv}">${info[1]}</small></div><button class="operation-delete" onclick="assign('${o.id}',null)" title="Remover">×</button></div>`:'<div class="empty-step">Nenhum montador alocado</div>'}<button class="step-add" onclick="openAssignModal('${o.id}')">＋ Alocar montador</button></div></div>`}).join(''); renderSuggestionPreview(); renderRouteEditor(); }
function renderRouteEditor(){ const el=document.querySelector('#routeEditor'); if(!el)return; const plan=activePlan(); el.innerHTML=state.employees.map(emp=>{const eligible=eligibleOperations(emp.id).map(o=>o.id);const route=routeFor(emp.id);const hasCustom=Array.isArray(plan.rotationRoutes?.[emp.id]);const currentEntry=Object.entries(plan.assignments||{}).find(([,employeeId])=>employeeId===emp.id);const currentOpId=currentEntry?.[0];const currentOp=state.operations.find(o=>o.id===currentOpId);if(!eligible.length)return `<div class="route-row"><div class="route-person"><strong>${escapeHtml(emp.name)}</strong><small>Nenhum step habilitado</small></div><span class="route-empty">Cadastre habilitações na matriz.</span></div>`;return `<div class="route-row"><div class="route-person"><strong>${escapeHtml(emp.name)}</strong><small>${hasCustom?'Rota personalizada':'Rota padrão pelos steps habilitados'}</small>${currentOp?`<span class="current-step-badge">Atual: <b>${escapeHtml(currentOp.code)}</b></span>`:'<span class="current-step-badge empty">Sem alocação atual</span>'}</div><div class="route-dropzone" data-route-employee="${emp.id}">${route.map((opId,i)=>{const op=state.operations.find(o=>o.id===opId);const isCurrent=opId===currentOpId;return `<div class="route-item ${isCurrent?'route-current':''}" draggable="true" data-route-employee="${emp.id}" data-route-index="${i}" title="${isCurrent?'Step atual do funcionário':'Arraste para ordenar'}"><span class="drag-handle">⋮⋮</span><span class="route-number">${i+1}</span><strong>${escapeHtml(op?.code||'Step removido')}</strong>${isCurrent?'<span class="current-tag">ATUAL</span>':''}</div>`}).join('')||'<span class="route-empty">Arraste steps habilitados para esta rota.</span>'}</div><button class="btn secondary route-reset" data-route-reset="${emp.id}">${hasCustom?'Usar padrão':'Rota padrão'}</button></div>`}).join(''); bindRouteEvents(); }
function eligibleOperations(empId){return state.operations.filter(o=>skill(empId,o.id)!=='sem_habilitacao');}
function routeFor(empId){const eligible=eligibleOperations(empId).map(o=>o.id);const saved=activePlan().rotationRoutes?.[empId];if(Array.isArray(saved)&&saved.length)return saved.filter(id=>eligible.includes(id));return eligible;}
function saveRouteOrder(empId,ids){const unique=[...new Set(ids)].filter(id=>eligibleOperations(empId).some(o=>o.id===id));const plan=activePlan();if(unique.length)plan.rotationRoutes[empId]=unique;else delete plan.rotationRoutes[empId];save();renderLineBoard();flash('Ordem da rota salva');}
function bindRouteEvents(){document.querySelectorAll('.route-item').forEach(item=>{item.addEventListener('dragstart',()=>{draggedRoute={empId:item.dataset.routeEmployee,index:Number(item.dataset.routeIndex)};item.classList.add('dragging')});item.addEventListener('dragend',()=>{draggedRoute=null;item.classList.remove('dragging')});});document.querySelectorAll('.route-dropzone').forEach(zone=>{zone.addEventListener('dragover',e=>e.preventDefault());zone.addEventListener('drop',e=>{e.preventDefault();if(!draggedRoute||draggedRoute.empId!==zone.dataset.routeEmployee)return;const target=e.target.closest('.route-item');const route=routeFor(draggedRoute.empId);const from=draggedRoute.index;let to=target?Number(target.dataset.routeIndex):route.length;if(from===to||(!target&&from===route.length-1))return;const [moved]=route.splice(from,1);if(target&&from<to)to--;route.splice(Math.max(0,to),0,moved);saveRouteOrder(draggedRoute.empId,route);});});document.querySelectorAll('[data-route-reset]').forEach(b=>b.onclick=()=>{delete activePlan().rotationRoutes[b.dataset.routeReset];save();renderLineBoard();flash('Rota padrão restaurada');});}
function openAssignModal(opId){modalMode='assign';modalId=opId;document.querySelector('#modalTitle').textContent='Alocar montador';document.querySelector('#modalLabel').textContent='Selecione o funcionário';const op=state.operations.find(o=>o.id===opId);const plan=activePlan();const eligible=state.employees.filter(e=>skill(e.id,opId)!=='sem_habilitacao'&&!Object.entries(plan.assignments).some(([id,emp])=>id!==opId&&emp===e.id));const options=eligible.map(e=>{const info=levelInfo(skill(e.id,opId));return `<option value="${e.id}">${escapeHtml(e.name)} (${info[1]})</option>`}).join('')||'<option value="">Nenhum montador habilitado ou disponível</option>';document.querySelector('#modalInput').outerHTML=`<select id="modalInput" class="modal-select"><option value="">Selecione...</option>${options}</select>`;document.querySelector('#modalBackdrop').classList.remove('hidden');}
function assign(opId,empId){const plan=activePlan();Object.keys(plan.assignments).forEach(id=>{if(id!==opId&&plan.assignments[id]===empId)delete plan.assignments[id]});if(empId)plan.assignments[opId]=empId;else delete plan.assignments[opId];save();render();flash(empId?'Montador alocado':'Alocação removida');}
function rotateAssignments(){const plan=activePlan();const current={...plan.assignments};const newAssignments={};Object.entries(current).forEach(([currentOpId,empId])=>{const route=routeFor(empId);if(!route.length)return;const index=route.indexOf(currentOpId);const start=index<0?0:index+1;const candidates=route.slice(start).concat(route.slice(0,start)).filter(id=>id!==currentOpId);const nextOpId=candidates.find(id=>!newAssignments[id]);if(nextOpId)newAssignments[nextOpId]=empId;else if(!newAssignments[currentOpId])newAssignments[currentOpId]=empId;});plan.assignments=newAssignments;plan.lastRun=today();if(plan.scheduledDate){const date=new Date(plan.scheduledDate+'T00:00:00');date.setDate(date.getDate()+(plan.frequency==='daily'?1:7));plan.scheduledDate=date.toISOString().slice(0,10);}}
function maybeRunScheduledRotation(){const plan=activePlan();const day=today();if(plan.mode==='automatic'&&plan.scheduledDate&&day>=plan.scheduledDate&&plan.lastRun!==day){rotateAssignments();save();}}
function runRotation(){rotateAssignments();save();render();flash('Rotação concluída com sucesso');}
function skillScore(value){return {titular:4,nivel_1:3,nivel_2:2,nivel_3:1,formacao_planejada:0}[value]??-1;}
function buildDistributionSuggestion(){const plan=activePlan();const current=plan.assignments||{};const used=new Set();const assignments={};const rows=[];const operations=[...state.operations].sort((a,b)=>{const ca=current[a.id]?1:0,cb=current[b.id]?1:0;return cb-ca});operations.forEach(op=>{const candidates=state.employees.filter(emp=>!used.has(emp.id)&&skillScore(skill(emp.id,op.id))>=0).sort((a,b)=>{const as=skillScore(skill(a.id,op.id)),bs=skillScore(skill(b.id,op.id));const ac=current[op.id]===a.id?1:0,bc=current[op.id]===b.id?1:0;return bc-ac||bs-as||a.name.localeCompare(b.name,'pt-BR')});const selected=candidates[0];if(selected){assignments[op.id]=selected.id;used.add(selected.id);}rows.push({opId:op.id,employeeId:selected?.id||'',level:selected?skill(selected.id,op.id):'',currentEmployeeId:current[op.id]||''});});return {assignments,rows};}
function renderSuggestionPreview(){const box=document.querySelector('#suggestionPreview');if(!box)return;if(!pendingSuggestion){box.classList.add('hidden');box.innerHTML='';return;}const assigned=pendingSuggestion.rows.filter(r=>r.employeeId).length;const changes=pendingSuggestion.rows.filter(r=>r.employeeId!==r.currentEmployeeId).length;box.classList.remove('hidden');box.innerHTML=`<div class="suggestion-head"><div><strong>Sugestão automática</strong><span>${assigned} de ${pendingSuggestion.rows.length} steps preenchidos · ${changes} alterações previstas</span></div><div class="suggestion-actions"><button class="btn secondary" id="cancelSuggestionBtn">Cancelar</button><button class="btn primary" id="applySuggestionBtn">Aplicar sugestão</button></div></div><div class="suggestion-list">${pendingSuggestion.rows.map(row=>{const op=state.operations.find(o=>o.id===row.opId);const current=state.employees.find(e=>e.id===row.currentEmployeeId);const selected=state.employees.find(e=>e.id===row.employeeId);const info=selected?levelInfo(row.level):null;return `<div class="suggestion-row"><strong>${escapeHtml(op?.code||'Step')}</strong><span>${current?`Atual: ${escapeHtml(current.name)}`:'Atual: vazio'}</span><span>${selected?`Sugestão: <b>${escapeHtml(selected.name)}</b> · ${info[1]}`:'Sem montador habilitado disponível'}</span></div>`}).join('')}</div>`;document.querySelector('#cancelSuggestionBtn').onclick=()=>{pendingSuggestion=null;renderSuggestionPreview();};document.querySelector('#applySuggestionBtn').onclick=()=>{activePlan().assignments={...pendingSuggestion.assignments};pendingSuggestion=null;save();renderLineBoard();flash('Distribuição sugerida aplicada');};}
function suggestDistribution(){pendingSuggestion=buildDistributionSuggestion();renderSuggestionPreview();flash('Sugestão pronta para revisão');}
function barDummy(){}
function bindMatrixEvents(){document.querySelectorAll('.cell-select').forEach(s=>s.onchange=()=>{state.skills[s.dataset.employee+'|'+s.dataset.operation]=s.value;save();render();flash('Habilitação salva');});document.querySelectorAll('[data-edit-employee]').forEach(b=>b.onclick=()=>openModal('employee',b.dataset.editEmployee));document.querySelectorAll('[data-delete-employee]').forEach(b=>b.onclick=()=>{if(confirm('Remover este funcionário da matriz?')){state.employees=state.employees.filter(e=>e.id!==b.dataset.deleteEmployee);state.linePlans.forEach(p=>{delete p.rotationRoutes[b.dataset.deleteEmployee];Object.keys(p.assignments).forEach(o=>{if(p.assignments[o]===b.dataset.deleteEmployee)delete p.assignments[o];});});save();render();flash('Funcionário removido');}});document.querySelectorAll('[data-edit-operation]').forEach(b=>b.onclick=()=>openModal('operation',b.dataset.editOperation));document.querySelectorAll('[data-delete-operation]').forEach(b=>b.onclick=()=>{if(confirm('Remover esta operação da matriz?')){state.operations=state.operations.filter(o=>o.id!==b.dataset.deleteOperation);state.linePlans.forEach(p=>{delete p.assignments[b.dataset.deleteOperation];Object.keys(p.rotationRoutes).forEach(e=>p.rotationRoutes[e]=p.rotationRoutes[e].filter(id=>id!==b.dataset.deleteOperation));});save();render();flash('Operação removida');}});}
function openLineModal(id=null){modalMode='line';modalId=id;document.querySelector('#modalTitle').textContent=id?'Editar linha':'Adicionar linha';document.querySelector('#modalLabel').textContent='Nome da linha';document.querySelector('#modalInput').value=id?(state.linePlans.find(l=>l.id===id)?.name||''):'';document.querySelector('#modalBackdrop').classList.remove('hidden');document.querySelector('#modalInput').focus();}
function openMatrixModal(id=null){modalMode='matrix';modalId=id;document.querySelector('#modalTitle').textContent=id?'Renomear tabela':'Nova tabela';document.querySelector('#modalLabel').textContent='Nome da tabela';document.querySelector('#modalInput').value=id?(state.matrices.find(m=>m.id===id)?.name||''):'';document.querySelector('#modalBackdrop').classList.remove('hidden');document.querySelector('#modalInput').focus();}
function openModal(mode,id=null){modalMode=mode;modalId=id;document.querySelector('#modalTitle').textContent=id?(mode==='employee'?'Editar funcionário':'Editar operação'):(mode==='employee'?'Adicionar funcionário':'Adicionar operação');document.querySelector('#modalLabel').textContent=mode==='employee'?'Nome completo':'Código da operação';document.querySelector('#modalInput').value=id?(mode==='employee'?state.employees.find(e=>e.id===id).name:state.operations.find(o=>o.id===id).code):'';document.querySelector('#modalBackdrop').classList.remove('hidden');document.querySelector('#modalInput').focus();}
function closeModal(){document.querySelector('#modalBackdrop').classList.add('hidden');const select=document.querySelector('.modal-select');if(select)select.outerHTML='<input id="modalInput" autocomplete="off">';modalMode=null;modalId=null;}
function saveModal(){const input=document.querySelector('#modalInput');const value=input.value.trim();if(modalMode==='assign'){if(value)assign(modalId,value);closeModal();return;}if(value.length<2)return;if(modalMode==='matrix'){if(modalId)state.matrices.find(m=>m.id===modalId).name=value;else{const id='table-'+Date.now();const copy=matrixFromState({employees:state.employees,operations:state.operations,skills:state.skills,linePlans:state.linePlans,activeLineId:state.activeLineId},id,value);state.matrices.push(copy);syncCurrentMatrix();activateMatrix(id);}save();closeModal();render();flash('Tabela salva');return;}if(modalMode==='line'){if(modalId)state.linePlans.find(l=>l.id===modalId).name=value;else{const id='line-'+Date.now();state.linePlans.push(blankPlan(id,value));state.activeLineId=id;}save();closeModal();renderLineBoard();flash('Linha salva');return;}if(modalMode==='employee'){if(modalId)state.employees.find(e=>e.id===modalId).name=value;else state.employees.push({id:'e'+Date.now(),name:value});}else{if(modalId)state.operations.find(o=>o.id===modalId).code=value;else state.operations.push({id:'o'+Date.now(),code:value});}save();closeModal();render();flash('Alteração salva');}
function deleteActiveLine(){if(state.linePlans.length<=1){flash('Mantenha pelo menos uma linha');return;}if(confirm('Remover esta linha?')){state.linePlans=state.linePlans.filter(l=>l.id!==activePlan().id);state.activeLineId=state.linePlans[0].id;save();renderLineBoard();flash('Linha removida');}}
function deleteActiveMatrix(){if(state.matrices.length<=1){flash('Mantenha pelo menos uma tabela');return;}const matrix=state.matrices.find(m=>m.id===state.activeMatrixId);if(confirm(`Remover a tabela "${matrix?.name||''}"?`)){state.matrices=state.matrices.filter(m=>m.id!==state.activeMatrixId);activateMatrix(state.matrices[0].id);save();render();flash('Tabela removida');}}
function exportJson(){syncCurrentMatrix();const payload={format:'Matriz Multi Skill Local',version:3,exportedAt:new Date().toISOString(),matrices:state.matrices,activeMatrixId:state.activeMatrixId,employees:state.employees,operations:state.operations,skills:state.skills,linePlans:state.linePlans,activeLineId:state.activeLineId};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='matriz-multi-skill-'+today()+'.json';a.click();URL.revokeObjectURL(url);flash('JSON exportado com sucesso');}
function validMatrix(data){if(!data||!Array.isArray(data.employees)||!Array.isArray(data.operations)||!data.skills||typeof data.skills!=='object'||!data.employees.length||!data.operations.length)return false;const eids=new Set(),oids=new Set(),allowed=new Set(levels.map(l=>l[0]));if(data.employees.some(e=>!e||typeof e.id!=='string'||!e.id.trim()||typeof e.name!=='string'||!e.name.trim()||eids.has(e.id)))return false;data.employees.forEach(e=>eids.add(e.id));if(data.operations.some(o=>!o||typeof o.id!=='string'||!o.id.trim()||typeof o.code!=='string'||!o.code.trim()||oids.has(o.id)))return false;data.operations.forEach(o=>oids.add(o.id));if(!Object.entries(data.skills).every(([k,v])=>{const p=k.split('|');return p.length===2&&eids.has(p[0])&&oids.has(p[1])&&typeof v==='string'&&allowed.has(v)}))return false;const plans=Array.isArray(data.linePlans)?data.linePlans:(data.linePlan?[data.linePlan]:[]);return plans.length>0&&plans.every(p=>p&&typeof p==='object'&&typeof (p.name||'Linha')==='string'&&(!p.assignments||Object.entries(p.assignments).every(([o,e])=>oids.has(o)&&eids.has(e))));}
function validImport(data){const matrices=Array.isArray(data?.matrices)&&data.matrices.length?data.matrices:[data];return matrices.every(validMatrix)&&(!data?.activeMatrixId||matrices.some(m=>m.id===data.activeMatrixId));}
function importJson(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!validImport(data))throw new Error('Formato inválido');const rawMatrices=Array.isArray(data.matrices)&&data.matrices.length?data.matrices:[data];const matrices=rawMatrices.map((m,i)=>matrixFromState(m,m.id||'table-'+(i+1),m.name||'Tabela '+(i+1)));state={matrices,activeMatrixId:data.activeMatrixId||matrices[0].id};activateMatrix(state.activeMatrixId);save();render();flash('JSON importado com sucesso');}catch(e){flash('Não foi possível importar este JSON');}};reader.readAsText(file);}
function flash(message){const n=document.createElement('div');n.textContent=message;n.style='position:fixed;right:20px;bottom:20px;background:#0f172a;color:white;padding:12px 16px;border-radius:10px;z-index:9;font-weight:600;font-size:13px;box-shadow:0 10px 30px #0003';document.body.appendChild(n);setTimeout(()=>n.remove(),1800);}
function showMatrix(){document.querySelector('#matriz').classList.remove('hidden');document.querySelector('.summary-grid').classList.remove('hidden');document.querySelector('#lineScreen').classList.add('hidden');document.querySelector('#matrixNav').classList.add('active');document.querySelector('#lineNav').classList.remove('active');}
function showLine(){document.querySelector('#matriz').classList.add('hidden');document.querySelector('.summary-grid').classList.add('hidden');document.querySelector('#lineScreen').classList.remove('hidden');document.querySelector('#matrixNav').classList.remove('active');document.querySelector('#lineNav').classList.add('active');renderLineBoard();}
document.querySelector('#searchInput').addEventListener('input',render);document.querySelector('#matrixSelect').onchange=e=>{syncCurrentMatrix();activateMatrix(e.target.value);save();render();};document.querySelector('#addMatrixBtn').onclick=()=>openMatrixModal();document.querySelector('#editMatrixBtn').onclick=()=>openMatrixModal(state.activeMatrixId);document.querySelector('#deleteMatrixBtn').onclick=deleteActiveMatrix;document.querySelector('#exportBtn').onclick=exportJson;document.querySelector('#importBtn').onclick=()=>document.querySelector('#importFile').click();document.querySelector('#importFile').onchange=e=>{if(e.target.files[0])importJson(e.target.files[0]);e.target.value=''};document.querySelector('#addEmployeeBtn').onclick=()=>openModal('employee');document.querySelector('#addOperationBtn').onclick=()=>openModal('operation');document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#cancelModal').onclick=closeModal;document.querySelector('#saveModal').onclick=saveModal;document.querySelector('#modalInput').onkeydown=e=>{if(e.key==='Enter')saveModal();if(e.key==='Escape')closeModal()};document.querySelector('#matrixNav').onclick=e=>{e.preventDefault();showMatrix();};document.querySelector('#lineNav').onclick=showLine;document.querySelector('#rotationDate').onchange=e=>{activePlan().scheduledDate=e.target.value;save();renderLineBoard();};document.querySelector('#rotationFrequency').onchange=e=>{activePlan().frequency=e.target.value;save();renderLineBoard();};document.querySelector('#rotationMode').onchange=e=>{activePlan().mode=e.target.value;save();renderLineBoard();};document.querySelector('#runRotationBtn').onclick=runRotation;document.querySelector('#suggestDistributionBtn').onclick=suggestDistribution;document.querySelector('#lineSelect').onchange=e=>{state.activeLineId=e.target.value;save();renderLineBoard();};document.querySelector('#addLineBtn').onclick=()=>openLineModal();document.querySelector('#editLineBtn').onclick=()=>openLineModal(activePlan().id);document.querySelector('#deleteLineBtn').onclick=deleteActiveLine;window.assign=assign;window.openAssignModal=openAssignModal;window.saveRouteOrder=saveRouteOrder;window.openLineModal=openLineModal;render();setInterval(()=>{const plan=activePlan();const day=today();if(plan.mode==='automatic'&&plan.scheduledDate&&day>=plan.scheduledDate&&plan.lastRun!==day){rotateAssignments();save();render();flash('Rotação automática executada');}},60000);
